import { useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Route, Routes } from "react-router-dom";
import {
  ALL_SKILLS,
  DEFAULT_MEMORY,
  DEFAULT_RULES,
  DEFAULT_WORKSPACES,
  EMPTY_MEMORY,
  T,
} from "./constants";
import { ModsView } from "./components/ModsView";
import { OnboardingWizard } from "./components/OnboardingWizard";
import { RulesView } from "./components/RulesView";
import { SettingsView } from "./components/SettingsView";
import { Sidebar } from "./components/Sidebar";
import { AdminDashboardView } from "./components/AdminDashboardView";
import { TaskFlowView } from "./components/TaskFlowView";
import { TopologyView } from "./components/TopologyView";
import { useActivityLog } from "./hooks/useActivityLog";
import { usePersistedState } from "./hooks/usePersistedState";
import { useTopology } from "./hooks/useTopology";
import { useWorkspace } from "./hooks/useWorkspace";
import type { AgentMemory, Lang, ThemeId, Workspace } from "./types";

export default function App() {
  const [lang, setLang] = usePersistedState<Lang>("app_lang", "zh");
  const [theme, setTheme] = usePersistedState<ThemeId>("app_theme", "dark");
  const [workspaces, setWorkspaces] = usePersistedState<Workspace[]>("workspaces", DEFAULT_WORKSPACES);
  const [activeWorkspaceId, setActiveWorkspaceId] = usePersistedState("active_ws_id", DEFAULT_WORKSPACES[0].id);
  const [memoryMap, setMemoryMap] = usePersistedState<Record<string, AgentMemory>>("memory_map", {});
  const [rules, setRules] = usePersistedState<string[]>("ai_rules_arr", DEFAULT_RULES);
  const [agentsEnabled, setAgentsEnabled] = usePersistedState("mods_agents_enabled", false);
  const [activeSkills, setActiveSkills] = usePersistedState<Record<string, boolean>>("mods_skills", {});
  const [hasOnboarded, setHasOnboarded] = usePersistedState("has_onboarded", false);
  const { activityEntries, recordActivity, clearActivityLog } = useActivityLog();
  const { sessionList, hasTopology, lastUpdatedSessionId } = useTopology();

  const fallbackMemory = activeWorkspaceId === DEFAULT_WORKSPACES[0].id ? DEFAULT_MEMORY : EMPTY_MEMORY;
  const {
    activeMemory,
    handleStatusChange,
    handleDescriptionChange,
    handleAddSubtask,
    handleDeleteTask,
  } = useWorkspace({
    activeWorkspaceId,
    fallbackMemory,
    memoryMap,
    setMemoryMap,
    workspaces,
    onActivity: recordActivity,
  });
  const t = T[lang];

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);

  useEffect(() => {
    if (!workspaces.some((workspace) => workspace.id === activeWorkspaceId) && workspaces[0]) {
      setActiveWorkspaceId(workspaces[0].id);
    }
  }, [activeWorkspaceId, setActiveWorkspaceId, workspaces]);

  useEffect(() => {
    const activeWorkspace = workspaces.find((workspace) => workspace.id === activeWorkspaceId);
    if (!activeWorkspace?.path || !agentsEnabled) {
      return;
    }

    const enabledSkills = ALL_SKILLS.filter((skill) => activeSkills[skill.id]);
    let markdown = "# AGENTS.md\n\n> This file is auto-generated by the AI Agent Topology Viewer.\n\n";
    markdown += "## Global Rules\n\n";
    rules.forEach((rule, index) => {
      markdown += `${index + 1}. ${rule}\n`;
    });

    if (enabledSkills.length > 0) {
      markdown += "\n## Active Skills\n\nThe following skills must be applied strictly:\n\n";
      enabledSkills.forEach((skill) => {
        markdown += `- **${skill.en}**: ${skill.zh}\n`;
      });
    }

    invoke("save_workspace_file", {
      path: activeWorkspace.path,
      filename: "AGENTS.md",
      content: markdown,
    }).catch(() => undefined);
  }, [activeSkills, activeWorkspaceId, agentsEnabled, rules, workspaces]);

  if (!hasOnboarded) {
    return (
      <OnboardingWizard
        lang={lang}
        onFinish={({ name, path }) => {
          const workspaceId = `ws-${Date.now()}`;
          const workspace = {
            id: workspaceId,
            name,
            lang: "TypeScript",
            path,
          };

          setWorkspaces((prev) => {
            const filtered = prev.filter((w) => w.path !== "");
            if (filtered.some((w) => w.path === path && w.name === name)) {
              return prev;
            }
            if (filtered.length === 0) {
              return [workspace];
            }
            return [...filtered, workspace];
          });
          setActiveWorkspaceId(workspaceId);
          setMemoryMap((prev) => ({ ...prev, [workspaceId]: EMPTY_MEMORY }));
          setHasOnboarded(true);
        }}
      />
    );
  }

  return (
    <div className="bg-grid relative h-screen w-full overflow-hidden font-sans">
      <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden" aria-hidden>
        <div
          className="absolute top-[-20%] left-[-10%] h-[50%] w-[50%] rounded-full opacity-30"
          style={{ background: "radial-gradient(circle, var(--orb1) 0%, transparent 70%)", filter: "blur(70px)" }}
        />
        <div
          className="absolute right-[-10%] bottom-[-20%] h-[40%] w-[40%] rounded-full opacity-20"
          style={{ background: "radial-gradient(circle, var(--orb2) 0%, transparent 70%)", filter: "blur(90px)" }}
        />
      </div>
      <div className="relative z-10 flex h-full">
        <Sidebar t={t} relaunchOnboarding={() => setHasOnboarded(false)} />
        <main className="ml-56 h-screen min-w-0 flex-1 overflow-hidden p-5">
          <Routes>
            <Route
              path="/"
              element={
                hasTopology ? (
                  <TopologyView
                    sessions={sessionList}
                    lastUpdatedSessionId={lastUpdatedSessionId}
                    activityEntries={activityEntries}
                    onClearActivityLog={clearActivityLog}
                    lang={lang}
                  />
                ) : (
                  <TaskFlowView
                    memory={activeMemory}
                    workspaces={workspaces}
                    activeWorkspaceId={activeWorkspaceId}
                    setActiveWorkspaceId={setActiveWorkspaceId}
                    onStatusChange={handleStatusChange}
                    onDescriptionChange={handleDescriptionChange}
                    onAddSubtask={handleAddSubtask}
                    onDeleteTask={handleDeleteTask}
                    activityEntries={activityEntries}
                    onClearActivityLog={clearActivityLog}
                    t={t}
                    lang={lang}
                  />
                )
              }
            />
            <Route path="/rules" element={<RulesView t={t} rules={rules} setRules={setRules} />} />
            <Route
              path="/mods"
              element={
                <ModsView
                  t={t}
                  lang={lang}
                  agentsEnabled={agentsEnabled}
                  setAgentsEnabled={setAgentsEnabled}
                  activeSkills={activeSkills}
                  setActiveSkills={setActiveSkills}
                />
              }
            />
            <Route
              path="/settings"
              element={
                <SettingsView
                  lang={lang}
                  setLang={setLang}
                  theme={theme}
                  setTheme={setTheme}
                  workspaces={workspaces}
                  setWorkspaces={setWorkspaces}
                  t={t}
                  relaunchOnboarding={() => setHasOnboarded(false)}
                />
              }
            />
            <Route
              path="/admin"
              element={
                <AdminDashboardView
                  theme={theme}
                  t={t}
                />
              }
            />
          </Routes>
        </main>
      </div>
    </div>
  );
}
