import type {
  AgentMemory,
  Lang,
  SkillCategory,
  SkillDefinition,
  ThemeDefinition,
  TranslationMessages,
  Workspace,
} from "./types";

export const T: Record<Lang, TranslationMessages> = {
  zh: {
    appTitle: "控制中心",
    taskFlow: "任務流程",
    rules: "規則",
    mods: "模組",
    settings: "設定",
    taskDetails: "任務詳情",
    taskId: "任務 ID",
    desc: "描述",
    deps: "依賴項目",
    noDeps: "無 — 根任務",
    aiFeedback: "AI 回饋",
    pending: "待處理",
    inProgress: "執行中",
    completed: "已完成",
    feedbackBadge: "含 AI 回饋",
    copy: "複製",
    aiRules: "AI 指令規則",
    addRule: "+ 新增指令",
    addRuleTitle: "新增 AI 指令",
    addRulePlaceholder: "輸入 AI 指令內容...",
    deleteRuleTitle: "刪除指令",
    deleteRuleConfirm: "確定要刪除這條指令嗎？",
    confirm: "確認",
    cancel: "取消",
    agentsMdToggle: "啟用 AGENTS.md 技能路由",
    agentsMdDesc: "啟用後，AI 將依照 AGENTS.md 規則自動選用對應技能提示詞。",
    skillsTitle: "技能提示詞",
    skillsDesc: "勾選後，所選技能將附加到 AI 指令中。",
    catBackend: "後端 & 架構",
    catMobile: "行動 & UI/UX",
    catTesting: "測試 & 文件",
    catQuality: "程式品質",
    settingsTitle: "設定",
    generalSettingsTab: "一般設定",
    usageGuideTab: "使用說明",
    aiGuideTab: "AI 指南",
    langLabel: "介面語言",
    themeLabel: "介面主題",
    themes: {
      light: "白色",
      tokyo: "Tokyo 電子風",
      dark: "黑色",
      forest: "森林綠",
      beige: "米棕色",
    },
    workspaces: "工作區",
    addWorkspace: "+ 新增工作區",
    removeWs: "移除",
    wsName: "工作區名稱",
    wsLang: "程式語言",
    wsPath: "JSON 路徑",
    wsPathPlaceholder: "D:\\Projects\\your-ai-project\\workspace",
    aiHowTitle: "AI 如何區分工作區？",
    aiHowBody: "每個工作區對應一個獨立的 agent_memory.json 路徑。讓 AI 代理（Codex、Antigravity 等）讀寫對應工作區的 JSON 路徑，即可讓多個 AI 各自操作獨立的任務圖，互不干擾。",
    activeWs: "當前工作區",
    howItWorks: "運作原理",
    howSteps: [
      {
        title: "共用 JSON 任務檔案",
        body: "Codex、Antigravity 等 AI 代理與本應用程式共享同一個 agent_memory.json。AI 寫入任務與回饋，使用者從 UI 更新狀態，兩者即時同步。",
      },
      {
        title: "檔案即時監聽",
        body: "Tauri 後端使用 notify crate 監聽 workspace 目錄。任何外部程式（包括 AI）修改 JSON 後，圖表會在毫秒內自動重新渲染。",
      },
      {
        title: "多 AI 並行協作",
        body: "Codex 可處理程式碼生成，Antigravity 可處理規劃與回顧。兩者均透過讀寫 agent_memory.json 的 status 與 ai_feedback 欄位來交換上下文，不需要直接通訊。",
      },
      {
        title: "人工監控",
        body: "使用者在 Task Flow 視圖中即時觀察 AI 進度，點擊節點改變狀態即可指揮 AI 進行下一步，無需手動編輯 JSON。",
      },
    ],
    aiGuideTitle: "與 AI 代理 (Codex/Antigravity) 協作指南",
    aiGuideSteps: [
      {
        title: "1. 配置獨立 Workspace",
        body: "在上方『工作區』區塊加入新專案，填寫專屬的 JSON 路徑（例如 D:\\ProjectA\\workspace）。輸入完畢後記得點擊「確認」按鈕來套用新路徑。",
      },
      {
        title: "Antigravity（規劃師）指南",
        body: "Antigravity 負責理解需求、拆解任務，並寫入 JSON。請對 Antigravity 下達類似以下指令：\n\n『你是一位 AI 開發規劃師。請幫我規劃一個登入系統，並將規劃結果更新到 D:\\Projects\\my-project\\workspace\\agent_memory.json。\n\n嚴格格式要求 — 每個任務節點必須且只能包含以下欄位：\n{  \"id\": \"task-001\",\n   \"description\": \"任務描述文字\",\n   \"status\": \"pending\",\n   \"dependencies\": [],\n   \"ai_feedback\": \"\" }\n\n• id — 唯一識別碼（如 task-001, task-002）\n• description — 任務說明（必填，圖表節點顯示此欄位）\n• status — 只能是 pending / in_progress / completed\n• dependencies — 前置任務 id 陣列（第一個任務設 []）\n• ai_feedback — 完成後的反省或備註\n\n禁止新增 title、design、findings 等自訂欄位，否則 UI 無法正確渲染。』",
      },
      {
        title: "Codex（執行者）指南",
        body: "Codex 負責撰寫實際程式碼。請對 Codex 下達類似以下指令：\n\n『請讀取 D:\\Projects\\my-project\\workspace\\agent_memory.json，尋找 status 為 in_progress 的任務。執行該任務後，如果完成，請將 JSON 中的狀態改為 completed，並在 ai_feedback 留下你修改了哪些檔案或遭遇的問題。』",
      },
      {
        title: "人類（你）的日常工作循環",
        body: "① 規劃階段：你要求 Antigravity 規劃任務。它將任務寫入 JSON（狀態為 pending）。\n② 監控與批准：你在 Topology Viewer 中看到新長出的圖表節點。點擊你想開始的任務，手動將狀態切換為 in_progress。這代表了你的批准執行。\n③ 執行階段：你命令 Codex 去處理 in_progress 的任務。\n④ 回顧階段：Codex 完成後，節點在 UI 變成 completed。點擊節點，右側滑出面板可閱讀 ai_feedback，確認 AI 的想法，並根據結果進行下一波規劃。",
      },
      {
        title: "確保 AI 吃到設定 (AGENTS.md)",
        body: "在開啟對話的當下，你必須給 AI 初始指令：「請詳閱工作目錄下的 AGENTS.md 並遵守規範」，AI 才會啟動並吃到所有的規則。",
      },
    ],
    opManual: "操作說明",
    opSteps: [
      {
        title: "載入任務",
        body: "Tauri 啟動時自動讀取 workspace/agent_memory.json。設定 AGENT_WORKSPACE_DIR 可指向自訂目錄。",
      },
      {
        title: "任務節點互動",
        body: "點選節點 → 右側詳情面板滑出。透過下拉選單改變狀態 → 即時寫回 JSON。",
      },
      {
        title: "多工作區支援",
        body: "在設定中新增多個工作區，每個工作區有獨立的任務圖。",
      },
      {
        title: "技能提示詞",
        body: "在模組頁勾選需要的技能，AI 閱讀 AGENTS.md 後會按照對應場景載入提示詞。",
      },
    ],
    aiTipsTitle: "AI 對話技巧",
    aiTipsDesc: "提煉自實際工作流，點擊展開。",
    tips: [
      {
        title: "📥 先餵資料，再說「stop」",
        body: "在要求 AI 執行任務之前，先分批提供所有背景資料，明確告知待命，讓 AI 充分吸收整體脈絡。",
      },
      {
        title: "版本鎖定規則",
        body: "在 AGENTS.md 中明確列出每種語言的最新穩定版本，強制 AI 使用最新語法。",
      },
      {
        title: "注入 .agent 技能庫",
        body: "將領域知識技能目錄提前塞入 .agent/skills/，讓 AI 在開發前讀取對應技能。",
      },
      {
        title: "結構化 JSON 溝通",
        body: "善用 agent_memory.json 的節點結構讓 AI 明確記錄每步，透過本工具視覺化整體進度。",
      },
      {
        title: "小批次迭代原則",
        body: "每次只讓 AI 處理一個明確子任務，完成後驗收再進行下一步。",
      },
    ],
    llmConfigTitle: "LLM 模型與服務設定",
    llmProviderLabel: "供應商 (Provider)",
    llmModelLabel: "模型 (Model)",
    llmApiKeyLabel: "API 金鑰 (API Key)",
    llmBaseUrlLabel: "自訂端點 (Base URL)",
    saveConfigBtn: "儲存模型設定",
    configSavedToast: "設定已成功更新！系統將立即套用新模型。",
    relaunchTutorialBtn: "重啟新手引導",
    adminConsole: "管理控制台",
    billingPlans: "租戶訂閱方案 (Stripe 狀態)",
    apiKeyRotation: "API 金鑰安全旋轉",
    realTimeUsage: "即時流量計費計量器",
    liveInterceptor: "Swarm 運行協同攔截畫布",
    ledgerVisualizer: "SHA-256 審計鏈校驗視覺化",
    pauseSwarm: "暫停 Swarm",
    resumeSwarm: "恢復 Swarm",
    hijackInput: "劫持輸入 (HITL 門禁)",
  },
  en: {
    appTitle: "Control Center",
    taskFlow: "Task Flow",
    rules: "Rules",
    mods: "MODs",
    settings: "Settings",
    taskDetails: "Task Details",
    taskId: "Task ID",
    desc: "Description",
    deps: "Dependencies",
    noDeps: "None — root task",
    aiFeedback: "AI Feedback",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    feedbackBadge: "AI Feedback attached",
    copy: "Copy",
    aiRules: "AI Instruction Rules",
    addRule: "+ Add Rule",
    addRuleTitle: "Add AI Instruction",
    addRulePlaceholder: "Enter AI instruction...",
    deleteRuleTitle: "Delete Instruction",
    deleteRuleConfirm: "Are you sure you want to delete this instruction?",
    confirm: "Confirm",
    cancel: "Cancel",
    agentsMdToggle: "Enable AGENTS.md Skill Routing",
    agentsMdDesc: "When enabled, the AI will automatically select skill prompts based on AGENTS.md routing rules.",
    skillsTitle: "Active Skill Prompts",
    skillsDesc: "Checked skills will be appended to AI instructions automatically.",
    catBackend: "Backend & Architecture",
    catMobile: "Mobile & UI/UX",
    catTesting: "Testing & Docs",
    catQuality: "Code Quality",
    settingsTitle: "Settings",
    generalSettingsTab: "General",
    usageGuideTab: "Guide",
    aiGuideTab: "AI Guide",
    langLabel: "UI Language",
    themeLabel: "UI Theme",
    themes: {
      light: "White",
      tokyo: "Tokyo Electronic",
      dark: "Black",
      forest: "Forest Green",
      beige: "Beige",
    },
    workspaces: "Workspaces",
    addWorkspace: "+ Add Workspace",
    removeWs: "Remove",
    wsName: "Workspace Name",
    wsLang: "Language",
    wsPath: "JSON Path",
    wsPathPlaceholder: "D:\\Projects\\your-ai-project\\workspace",
    aiHowTitle: "How does AI distinguish workspaces?",
    aiHowBody: "Each workspace maps to a unique agent_memory.json file path. Configure your AI agents (Codex, Antigravity, etc.) to read from and write to each workspace's designated JSON path. This lets multiple AIs operate on completely independent task graphs without interfering with each other.",
    activeWs: "Active Workspace",
    howItWorks: "How It Works",
    howSteps: [
      {
        title: "Shared JSON Task File",
        body: "Codex, Antigravity, and this app share the same agent_memory.json. AIs write tasks and feedback; users update status from the UI — everything syncs in real time.",
      },
      {
        title: "Live File Watching",
        body: "The Tauri backend uses the notify crate to watch the workspace directory. Any external program modifying the JSON causes the graph to re-render within milliseconds.",
      },
      {
        title: "Multi-AI Parallel Collaboration",
        body: "Codex handles code generation, Antigravity handles planning and review. Both exchange context through status and ai_feedback fields without direct communication.",
      },
      {
        title: "Human Oversight",
        body: "Users observe AI progress in real time. Clicking a node to change its status directly directs the AI to the next step — no manual JSON editing required.",
      },
    ],
    aiGuideTitle: "Collaboration Guide: Codex / Antigravity",
    aiGuideSteps: [
      {
        title: "1. Configure Workspace",
        body: "Add a new workspace and specify an absolute JSON path (e.g., D:\\Proj\\workspace) so your AI agents don't step on each other. Remember to click 'Confirm' after entering the path to apply the change.",
      },
      {
        title: "Antigravity (Planner) Guide",
        body: "Antigravity understands requirements, decomposes tasks, and writes them to JSON. Give it a prompt like:\n\n'You are an AI development planner. Plan a login system and update D:\\Projects\\my-project\\workspace\\agent_memory.json.\n\nStrict format required — each task node must contain ONLY these fields:\n{  \"id\": \"task-001\",\n   \"description\": \"Task description text\",\n   \"status\": \"pending\",\n   \"dependencies\": [],\n   \"ai_feedback\": \"\" }\n\n• id — unique identifier (e.g. task-001, task-002)\n• description — task description (required, displayed on graph nodes)\n• status — must be pending / in_progress / completed\n• dependencies — array of prerequisite task ids (first task uses [])\n• ai_feedback — reflection or notes after completion\n\nDo NOT add custom fields like title, design, findings, etc. The UI cannot render them.'",
      },
      {
        title: "Codex (Executor) Guide",
        body: "Codex writes actual code. Give it a prompt like:\n\n'Read D:\\Projects\\my-project\\workspace\\agent_memory.json and find tasks with status in_progress. Execute the task, then change the JSON status to completed and leave a note in ai_feedback describing which files you modified or issues encountered.'",
      },
      {
        title: "Human (You) Daily Workflow",
        body: "① Planning: Ask Antigravity to plan tasks. It writes them to JSON (status: pending).\n② Monitor & Approve: New nodes appear in Topology Viewer. Click a task you want to start and switch it to in_progress — this is your approval.\n③ Execution: Command Codex to handle in_progress tasks.\n④ Review: After Codex finishes, nodes turn completed. Click a node to open the detail panel, read ai_feedback, confirm the AI's work, then begin the next planning cycle.",
      },
      {
        title: "Ensuring AI reads AGENTS.md",
        body: "This UI toggle prepares the markdown file, but you must still explicitly tell your AI: 'Read AGENTS.md and follow its rules' when you start the conversation.",
      },
    ],
    opManual: "Operating Manual",
    opSteps: [
      {
        title: "Load Tasks",
        body: "Tauri reads workspace/agent_memory.json on startup. Set AGENT_WORKSPACE_DIR to use a custom directory.",
      },
      {
        title: "Node Interaction",
        body: "Click a node → the detail panel slides out. Change status via dropdown → writes back to JSON instantly.",
      },
      {
        title: "Multi-Workspace Support",
        body: "Add multiple workspaces in Settings, each with its own independent task graph.",
      },
      {
        title: "Skill Prompts",
        body: "Check needed skills in MODs. The AI will load corresponding prompts based on AGENTS.md rules.",
      },
    ],
    aiTipsTitle: "AI Prompting Techniques",
    aiTipsDesc: "Extracted from real workflows. Click to expand.",
    tips: [
      {
        title: "📥 Feed Data First, Then Say 'stop'",
        body: "Before asking the AI to execute, feed all background data incrementally and tell it to stand by until you say 'stop'.",
      },
      {
        title: "Lock Version Rules",
        body: "Clearly list the latest stable version of every language in AGENTS.md, forcing the AI to use current syntax.",
      },
      {
        title: "Inject .agent Skill Libraries",
        body: "Pre-load domain knowledge skill directories into .agent/skills/ so the AI reads them before development.",
      },
      {
        title: "Structured JSON Communication",
        body: "Use the node structure of agent_memory.json to let the AI explicitly record each step.",
      },
      {
        title: "Small Batch Iteration Principle",
        body: "Let the AI handle one clear sub-task at a time, verify, then proceed to the next.",
      },
    ],
    llmConfigTitle: "LLM Model Configuration",
    llmProviderLabel: "Provider",
    llmModelLabel: "Model",
    llmApiKeyLabel: "API Key",
    llmBaseUrlLabel: "Base URL",
    saveConfigBtn: "Save LLM Config",
    configSavedToast: "Configuration saved successfully! The new model is now active.",
    relaunchTutorialBtn: "Relaunch Tutorial",
    adminConsole: "Admin Console",
    billingPlans: "Tenant Billing Plans (Stripe Status)",
    apiKeyRotation: "API Key Rotation",
    realTimeUsage: "Real-time Usage Meters",
    liveInterceptor: "Swarm Live Interceptor Canvas",
    ledgerVisualizer: "Ledger Validation Visualizer",
    pauseSwarm: "Pause Swarm",
    resumeSwarm: "Resume Swarm",
    hijackInput: "Hijack Input (HITL Gate)",
  },
  ja: {
    appTitle: "コントロールセンター",
    taskFlow: "タスクフロー",
    rules: "ルール",
    mods: "モジュール",
    settings: "設定",
    taskDetails: "タスク詳細",
    taskId: "タスク ID",
    desc: "説明",
    deps: "依存関係",
    noDeps: "なし — ルートタスク",
    aiFeedback: "AI フィードバック",
    pending: "保留中",
    inProgress: "進行中",
    completed: "完了",
    feedbackBadge: "💬 AI フィードバックあり",
    copy: "📋 コピー",
    aiRules: "AI 指示ルール",
    addRule: "+ ルールを追加",
    addRuleTitle: "AI 指示の追加",
    addRulePlaceholder: "AIへの指示を入力...",
    deleteRuleTitle: "指示の削除",
    deleteRuleConfirm: "この指示を削除してもよろしいですか？",
    confirm: "確認",
    cancel: "キャンセル",
    agentsMdToggle: "AGENTS.md スキルルーティングを有効化",
    agentsMdDesc: "有効にすると、AIはAGENTS.mdのルーティングルールに基づいて自動的にスキルプロンプトを選択します。",
    skillsTitle: "有効なスキルプロンプト",
    skillsDesc: "チェックされたスキルは自動的にAI指示に追加されます。",
    catBackend: "バックエンド & アーキテクチャ",
    catMobile: "モバイル & UI/UX",
    catTesting: "テスト & ドキュメント",
    catQuality: "コード品質",
    settingsTitle: "設定",
    generalSettingsTab: "一般",
    usageGuideTab: "ガイド",
    aiGuideTab: "AIガイド",
    langLabel: "UI言語",
    themeLabel: "UIテーマ",
    themes: {
      light: "ライト",
      tokyo: "Tokyo 電子風",
      dark: "ダーク",
      forest: "フォレスト",
      beige: "ベージュ",
    },
    workspaces: "ワークスペース",
    addWorkspace: "+ ワークスペースを追加",
    removeWs: "削除",
    wsName: "ワークスペース名",
    wsLang: "言語",
    wsPath: "JSON パス",
    wsPathPlaceholder: "D:\\Projects\\your-ai-project\\workspace",
    aiHowTitle: "AIはどのようにワークスペースを区別しますか？",
    aiHowBody: "各ワークスペースは、固有の agent_memory.json ファイルパスにマッピングされます。AIエージェント（Codex、Antigravityなど）がそれぞれの指定されたJSONパスを読み書きするように設定します。これにより、複数のAIが互いに干渉することなく、完全に独立したタスクグラフで動作できるようになります。",
    activeWs: "アクティブなワークスペース",
    howItWorks: "動作原理",
    howSteps: [
      {
        title: "共有されたJSONタスクファイル",
        body: "Codex、Antigravity、およびこのアプリは同じ agent_memory.json を共有します。AIがタスクとフィードバックを書き込み、ユーザーがUIからステータスを更新することで、すべてがリアルタイムで同期されます。",
      },
      {
        title: "リアルタイムファイル監視",
        body: "Tauriバックエンドはnotifyクレートを使用してワークスペースディレクトリを監視します。外部プログラムがJSONを変更すると、グラフはミリ秒以内に自動的に再レンダリングされます。",
      },
      {
        title: "複数AIの並行協作",
        body: "Codexがコード生成を処理し、Antigravityが計画とレビューを処理します。双方は直接通信することなく、statusとai_feedbackフィールドを介してコンテキストを交換します。",
      },
      {
        title: "人間の監視",
        body: "ユーザーはAIの進捗をリアルタイムで観察します。ノードをクリックしてステータスを変更するだけで、AIを次のステップに直接指示できます。手動でJSONを編集する必要はありません。",
      },
    ],
    aiGuideTitle: "コラボレーションガイド: Codex / Antigravity",
    aiGuideSteps: [
      {
        title: "1. ワークスペースの構成",
        body: "新しいワークスペースを追加し、絶対JSONパス（例：D:\\Proj\\workspace）を指定して、AIエージェントが互いに干渉しないようにします。パスを入力した後は、必ず「確認」ボタンをクリックして変更を適用してください。",
      },
      {
        title: "Antigravity (プランナー) ガイド",
        body: "Antigravityは要件を理解し、タスクを分解してJSONに書き込みます。以下のようなプロンプトを指定してください：\n\n「あなたはAI開発プランナーです。My First Projectの実行可能なタスク計画を分解し、結果を次のパスに書き込んでください：D:\\Projects\\my-project\\workspace\\agent_memory.json\n\n厳格な形式要件 — 各タスクノードには以下のフィールドのみを含める必要があります：\n{  \"id\": \"task-001\",\n   \"description\": \"タスクの説明\",\n   \"status\": \"pending\",\n   \"dependencies\": [],\n   \"ai_feedback\": \"\" }\n\n• id — 一意の識別子（例：task-001、task-002）\n• description — タスクの説明（必須、グラフノードに表示されます）\n• status — pending / in_progress / completed のいずれかである必要があります\n• dependencies — 前提条件タスクIDの配列（最初のタスクは []）\n• ai_feedback — 完了後の振り返りやメモ\n\ntitle、design、findings などのカスタムフィールドは追加しないでください。UIが正しくレンダリングできなくなります。」",
      },
      {
        title: "Codex (実行者) ガイド",
        body: "Codexは実際のコードを記述します。以下のようなプロンプトを指定してください：\n\n「D:\\Projects\\my-project\\workspace\\agent_memory.json を読み込み、ステータスが in_progress のタスクを見つけて実行してください。完了したら、JSONのステータスを completed に変更し、変更したファイルや発生した問題を記述したメモを ai_feedback に残してください。」",
      },
      {
        title: "人間（あなた）の日常のワークフロー",
        body: "① 計画段階：Antigravityにタスクの計画を依頼します。タスクがJSONに書き込まれます（ステータス：pending）。\n② 監視と承認：Topology Viewerに新しいノードが表示されます。開始したいタスクをクリックし、ステータスを in_progress に切り替えます。これがあなたの承認です。\n③ 実行段階：in_progress タスクを処理するようCodexに指示します。\n④ レビュー：Codexが終了すると、ノードは completed に変わります。ノードをクリックして詳細パネルを開き、ai_feedbackを読み、AIの作業を確認して、次の計画サイクルを開始します。",
      },
      {
        title: "AIがAGENTS.mdを読み込むようにする",
        body: "このUIの切り替えによってマークダウンファイルが準備されますが、会話を開始する際には、AIに対して「AGENTS.mdを読み込み、そのルールに従ってください」と明示的に指示する必要があります。",
      },
    ],
    opManual: "操作マニュアル",
    opSteps: [
      {
        title: "タスクの読み込み",
        body: "Tauriは起動時に自動的に workspace/agent_memory.json を読み込みます。カスタムディレクトリを使用するには、AGENT_WORKSPACE_DIRを設定します。",
      },
      {
        title: "ノードのインタラクション",
        body: "ノードをクリックすると詳細パネルがスライドアウトします。ドロップダウン経由でステータスを変更すると、即座にJSONに書き戻されます。",
      },
      {
        title: "複数ワークスペースのサポート",
        body: "設定で複数のワークスペースを追加でき、それぞれが独立したタスクグラフを持ちます。",
      },
      {
        title: "スキルプロンプト",
        body: "モジュールで必要なスキルにチェックを入れます。AIはAGENTS.mdのルールに基づいて対応するプロンプトをロードします。",
      },
    ],
    aiTipsTitle: "AI プロンプトテクニック",
    aiTipsDesc: "実際のワークフローから抽出されました。クリックして展開します。",
    tips: [
      {
        title: "📥 最初にデータを入力し、次に「stop」と言う",
        body: "AIに実行を依頼する前に、すべての背景データを段階的に入力し、「stop」と言うまで待機するように指示します。",
      },
      {
        title: "バージョンロックルール",
        body: "AGENTS.mdで各言語の最新の安定バージョンを明示的にリストし、AIに最新の構文を使用させます。",
      },
      {
        title: ".agent スキルライブラリの注入",
        body: "ドメイン知識のスキルディレクトリを事前に .agent/skills/ にロードし、開発前にAIが読み込めるようにします。",
      },
      {
        title: "構造化JSONによるコミュニケーション",
        body: "agent_memory.json のノード構造を活用して、AIが各ステップを明示的に記録できるようにします。",
      },
      {
        title: "小規模バッチイテレーション原則",
        body: "AIに一度に1つの明確なサブタスクを処理させ、検証してから次に進みます。",
      },
    ],
    llmConfigTitle: "LLM モデル設定",
    llmProviderLabel: "プロバイダー",
    llmModelLabel: "モデル",
    llmApiKeyLabel: "API キー",
    llmBaseUrlLabel: "ベース URL",
    saveConfigBtn: "LLM設定を保存",
    configSavedToast: "設定が正常に保存されました！新しいモデルがアクティブになりました。",
    relaunchTutorialBtn: "チュートリアルを再起動",
    adminConsole: "管理コンソール",
    billingPlans: "テナント購読プラン (Stripe ステータス)",
    apiKeyRotation: "API キーのローテーション",
    realTimeUsage: "リアルタイム使用量メーター",
    liveInterceptor: "Swarm ライブインターセプターキャンバス",
    ledgerVisualizer: "レジャー検証ビジュアライザ",
    pauseSwarm: "スウォームを一時停止",
    resumeSwarm: "スウォームを再開",
    hijackInput: "入力をハイジャック (HITL ゲート)",
  },
  fr: {
    appTitle: "Centre de Contrôle",
    taskFlow: "Flux de Tâches",
    rules: "Règles",
    mods: "Modules",
    settings: "Paramètres",
    taskDetails: "Détails de la Tâche",
    taskId: "ID de la Tâche",
    desc: "Description",
    deps: "Dépendances",
    noDeps: "Aucune — Tâche racine",
    aiFeedback: "Retour de l'IA",
    pending: "En attente",
    inProgress: "En cours",
    completed: "Terminé",
    feedbackBadge: "💬 Retour de l'IA joint",
    copy: "📋 Copier",
    aiRules: "Règles d'instruction de l'IA",
    addRule: "+ Ajouter une règle",
    addRuleTitle: "Ajouter une instruction IA",
    addRulePlaceholder: "Entrez l'instruction IA...",
    deleteRuleTitle: "Supprimer l'instruction",
    deleteRuleConfirm: "Êtes-vous sûr de vouloir supprimer cette instruction ?",
    confirm: "Confirmer",
    cancel: "Annuler",
    agentsMdToggle: "Activer le routage des compétences AGENTS.md",
    agentsMdDesc: "Lorsqu'il est activé, l'IA sélectionnera automatiquement les invites de compétences basées sur les règles de routage d'AGENTS.md.",
    skillsTitle: "Invites de compétences actives",
    skillsDesc: "Les compétences cochées seront automatiquement ajoutées aux instructions de l'IA.",
    catBackend: "Backend & Architecture",
    catMobile: "Mobile & UI/UX",
    catTesting: "Tests & Docs",
    catQuality: "Qualité du Code",
    settingsTitle: "Paramètres",
    generalSettingsTab: "Général",
    usageGuideTab: "Guide",
    aiGuideTab: "Guide IA",
    langLabel: "Langue de l'UI",
    themeLabel: "Thème de l'UI",
    themes: {
      light: "Clair",
      tokyo: "Tokyo Électronique",
      dark: "Sombre",
      forest: "Forêt",
      beige: "Beige",
    },
    workspaces: "Espaces de travail",
    addWorkspace: "+ Ajouter un espace",
    removeWs: "Supprimer",
    wsName: "Nom de l'espace",
    wsLang: "Langage",
    wsPath: "Chemin JSON",
    wsPathPlaceholder: "D:\\Projects\\your-ai-project\\workspace",
    aiHowTitle: "Comment l'IA distingue-t-elle les espaces ?",
    aiHowBody: "Chaque espace de travail est associé à un chemin de fichier agent_memory.json unique. Configurez vos agents IA (Codex, Antigravity, etc.) pour lire et écrire dans le chemin JSON désigné de chaque espace de travail. Cela permet à plusieurs IA de fonctionner sur des graphes de tâches complètement indépendants sans interférer les unes avec les autres.",
    activeWs: "Espace de travail actif",
    howItWorks: "Comment ça marche",
    howSteps: [
      {
        title: "Fichier de tâches JSON partagé",
        body: "Codex, Antigravity et cette application partagent le même agent_memory.json. Les IA écrivent les tâches et les retours; les utilisateurs mettent à jour le statut depuis l'UI — tout se synchronise en temps réel.",
      },
      {
        title: "Surveillance des fichiers en direct",
        body: "Le backend Tauri utilise le crate notify pour surveiller le répertoire de l'espace de travail. Tout programme externe modifiant le JSON provoque une mise à jour du graphe en quelques millisecondes.",
      },
      {
        title: "Collaboration parallèle multi-IA",
        body: "Codex gère la génération de code, Antigravity gère la planification et la révision. Les deux échangent le contexte via les champs status et ai_feedback sans communication directe.",
      },
      {
        title: "Supervision humaine",
        body: "Les utilisateurs observent la progression de l'IA en temps réel. Cliquer sur un nœud pour modifier son statut dirige directement l'IA vers l'étape suivante — aucune modification manuelle du JSON requise.",
      },
    ],
    aiGuideTitle: "Guide de Collaboration: Codex / Antigravity",
    aiGuideSteps: [
      {
        title: "1. Configurer l'espace de travail",
        body: "Ajoutez un nouvel espace de travail et spécifiez un chemin JSON absolu (ex: D:\\Proj\\workspace) pour que vos agents IA ne se marchent pas dessus. N'oubliez pas de cliquer sur le bouton 'Confirmer' après avoir saisi le chemin pour appliquer le changement.",
      },
      {
        title: "Guide Antigravity (Planificateur)",
        body: "Antigravity comprend les exigences, décompose les tâches et les écrit dans le JSON. Donnez-lui une invite comme :\n\n'Vous êtes un planificateur de développement IA. Planifiez un plan de tâches exécutable pour « My First Project » et mettez à jour le résultat à l'adresse suivante : D:\\Projects\\my-project\\workspace\\agent_memory.json\n\nExigence de format strict — chaque nœud de tâche doit contenir UNIQUEMENT ces champs :\n{  \"id\": \"task-001\",\n   \"description\": \"Description de la tâche\",\n   \"status\": \"pending\",\n   \"dependencies\": [],\n   \"ai_feedback\": \"\" }\n\n• id — identifiant unique (ex: task-001, task-002)\n• description — description de la tâche (obligatoire, affichée sur les nœuds du graphe)\n• status — doit être pending / in_progress / completed\n• dependencies — tableau d'identifiants de tâches prérequises (la première tâche utilise [])\n• ai_feedback — réflexion ou notes après réalisation\n\nN'ajoutez PAS de champs personnalisés comme title, design, findings, etc. L'UI ne pourra pas les rendre.'",
      },
      {
        title: "Guide Codex (Exécuteur)",
        body: "Codex écrit le code réel. Donnez-lui une invite comme :\n\n'Lisez D:\\Projects\\my-project\\workspace\\agent_memory.json et trouvez les tâches avec le statut in_progress. Exécutez la tâche, puis changez le statut JSON en completed et laissez une note dans ai_feedback décrivant les fichiers modifiés ou les problèmes rencontrés.'",
      },
      {
        title: "Flux de travail quotidien humain (Vous)",
        body: "① Planification : Demandez à Antigravity de planifier les tâches. Il les écrit dans le JSON (statut: pending).\n② Surveillance & Approbation : De nouveaux nœuds apparaissent dans le Topology Viewer. Cliquez sur une tâche que vous souhaitez démarrer et passez-la à in_progress — c'est votre approbation.\n③ Exécution : Commandez à Codex de gérer les tâches in_progress.\n④ Révision : Une fois que Codex a terminé, les nœuds deviennent completed. Cliquez sur un nœud pour ouvrir le panneau de détails, lisez ai_feedback, confirmez le travail de l'IA, puis commencez le cycle de planification suivant.",
      },
      {
        title: "S'assurer que l'IA lit AGENTS.md",
        body: "Cette bascule de l'UI prépare le fichier markdown, mais vous devez toujours indiquer explicitement à votre IA : 'Lisez AGENTS.md et suivez ses règles' lorsque vous commencez la conversation.",
      },
    ],
    opManual: "Manuel d'utilisation",
    opSteps: [
      {
        title: "Charger les tâches",
        body: "Tauri lit automatiquement workspace/agent_memory.json au démarrage. Définissez AGENT_WORKSPACE_DIR pour utiliser un répertoire personnalisé.",
      },
      {
        title: "Interaction avec les nœuds",
        body: "Cliquez sur un nœud → le panneau de détails glisse vers l'extérieur. Modifiez le statut via le menu déroulant → écrit instantanément dans le JSON.",
      },
      {
        title: "Support multi-espaces",
        body: "Ajoutez plusieurs espaces de travail dans les Paramètres, chacun ayant son propre graphe de tâches indépendant.",
      },
      {
        title: "Invites de compétences",
        body: "Cochez les compétences nécessaires dans Modules. L'IA chargera les invites correspondantes basées sur les règles d'AGENTS.md.",
      },
    ],
    aiTipsTitle: "Techniques d'invites de l'IA",
    aiTipsDesc: "Extrait des flux de travail réels. Cliquez pour développer.",
    tips: [
      {
        title: "📥 Fournir les données d'abord, puis dire «stop»",
        body: "Avant de demander à l'IA d'exécuter, fournissez toutes les données de contexte de manière incrémentielle et dites-lui de patienter jusqu'à ce que vous disiez «stop».",
      },
      {
        title: "Règle de verrouillage de version",
        body: "Listez clairement la dernière version stable de chaque langage dans AGENTS.md, forçant l'IA à utiliser une syntaxe actuelle.",
      },
      {
        title: "Injecter les bibliothèques de compétences .agent",
        body: "Préchargez les répertoires de compétences de connaissances du domaine dans .agent/skills/ afin que l'IA les lise avant le développement.",
      },
      {
        title: "Communication JSON structurée",
        body: "Utilisez la structure de nœud de agent_memory.json pour permettre à l'IA d'enregistrer explicitement chaque étape.",
      },
      {
        title: "Principe d'itération par lots limités",
        body: "Laissez l'IA gérer une sous-tâche claire à la fois, vérifiez, puis passez à la suivante.",
      },
    ],
    llmConfigTitle: "Configuration du modèle LLM",
    llmProviderLabel: "Fournisseur",
    llmModelLabel: "Modèle",
    llmApiKeyLabel: "Clé API",
    llmBaseUrlLabel: "URL de base",
    saveConfigBtn: "Enregistrer la config LLM",
    configSavedToast: "Configuration enregistrée avec succès ! Le nouveau modèle est maintenant actif.",
    relaunchTutorialBtn: "Relancer le didacticiel",
    adminConsole: "Console d'Administration",
    billingPlans: "Plans de Facturation des Locataires (Stripe)",
    apiKeyRotation: "Rotation des Clés API",
    realTimeUsage: "Compteurs d'Utilisation en Temps Réel",
    liveInterceptor: "Canevas d'Interception Swarm en Direct",
    ledgerVisualizer: "Visualiseur de Validation du Registre",
    pauseSwarm: "Suspendre le Swarm",
    resumeSwarm: "Reprendre le Swarm",
    hijackInput: "Détourner l'Entrée (HITL)",
  },
};

export const ALL_LANGS = [
  "TypeScript",
  "JavaScript",
  "Python",
  "Rust",
  "Go",
  "Dart",
  "Swift",
  "Kotlin",
  "C++",
  "C#",
  "Java",
  "Ruby",
  "PHP",
];

export const THEME_LIST: ThemeDefinition[] = [
  { id: "light", accentNode: "#0284c7" },
  { id: "tokyo", accentNode: "#ff2eff" },
  { id: "dark", accentNode: "#6366f1" },
  { id: "forest", accentNode: "#22c55e" },
  { id: "beige", accentNode: "#b45309" },
];

export const ALL_SKILLS: SkillDefinition[] = [
  { id: "backend-architect", cat: "backend", zh: "後端架構師", en: "Backend Architect" },
  { id: "api-design-principles", cat: "backend", zh: "API 設計原則", en: "API Design Principles" },
  { id: "data-pipeline-architect", cat: "backend", zh: "資料管線架構師", en: "Data Pipeline Architect" },
  { id: "fastapi-swagger-sync", cat: "backend", zh: "FastAPI Swagger 同步", en: "FastAPI Swagger Sync" },
  { id: "graphql-resolver-gen", cat: "backend", zh: "GraphQL 解析器生成", en: "GraphQL Resolver Gen" },
  { id: "api-contract-sync", cat: "backend", zh: "API 合約同步", en: "API Contract Sync" },
  { id: "react-native-expert", cat: "mobile", zh: "React Native 專家", en: "React Native Expert" },
  { id: "react-native-perf-boost", cat: "mobile", zh: "React Native 效能優化", en: "React Native Perf Boost" },
  { id: "mobile-sensor-integrator", cat: "mobile", zh: "行動感測器整合", en: "Mobile Sensor Integrator" },
  { id: "ui-ux-pro-max-skill", cat: "mobile", zh: "UI/UX 專業技能", en: "UI/UX Pro Max" },
  { id: "gamification-ui-kit", cat: "mobile", zh: "遊戲化 UI 套件", en: "Gamification UI Kit" },
  { id: "design-to-code-bridge", cat: "mobile", zh: "設計轉程式碼橋接", en: "Design to Code Bridge" },
  { id: "tdd-workflows-tdd-cycle", cat: "testing", zh: "TDD 工作流程", en: "TDD Workflows" },
  { id: "qa-auto-tester-pro", cat: "testing", zh: "QA 自動測試", en: "QA Auto Tester Pro" },
  { id: "doc-gen-pro", cat: "testing", zh: "文件生成器", en: "Doc Gen Pro" },
  { id: "code-refactoring-refactor-clean", cat: "quality", zh: "程式碼重構", en: "Code Refactoring" },
  { id: "code-review-ai-ai-review", cat: "quality", zh: "AI 程式碼審查", en: "Code Review AI" },
  { id: "python-ast-visualizer", cat: "quality", zh: "Python AST 視覺化", en: "Python AST Visualizer" },
  { id: "git-commit-standardizer", cat: "quality", zh: "Git 提交標準化", en: "Git Commit Standardizer" },
  { id: "python-algo-optimizer", cat: "quality", zh: "Python 演算法優化", en: "Python Algo Optimizer" },
];

export const CAT_KEYS: SkillCategory[] = ["backend", "mobile", "testing", "quality"];

export const DEFAULT_MEMORY: AgentMemory = {
  tasks: [
    {
      id: "task-001",
      description: "Initialize desktop topology viewer scaffold",
      status: "completed",
      dependencies: [],
      ai_feedback: "Tauri 2.0 + Vite scaffolded cleanly. Recommend pinning Rust edition to 2021.",
      tasks: [
        {
          id: "task-001-01",
          description: "Set up Tauri + React + Vite architecture",
          status: "completed",
          dependencies: ["task-001"],
        },
        {
          id: "task-001-02",
          description: "Create fixed sidebar and route shells",
          status: "completed",
          dependencies: ["task-001-01"],
        },
      ],
    },
    {
      id: "task-002",
      description: "Render DAG from agent memory with dagre auto-layout",
      status: "in_progress",
      dependencies: ["task-001-02"],
      ai_feedback: "Dagre LR layout wired. nodesep=60, ranksep=130. No overlaps on complex trees.",
      tasks: [
        {
          id: "task-002-01",
          description: "Map dependencies into directed edges",
          status: "completed",
          dependencies: ["task-002"],
        },
        {
          id: "task-002-02",
          description: "Display glowing status task cards",
          status: "in_progress",
          dependencies: ["task-002-01"],
          ai_feedback: "In-progress nodes now emit pulsing amber glow via CSS keyframe animation.",
        },
      ],
    },
    {
      id: "task-003",
      description: "Two-way sync: write status changes back to JSON",
      status: "completed",
      dependencies: ["task-002-02"],
      ai_feedback: "save_agent_memory Tauri IPC implemented. Optimistic UI update fires before async write.",
    },
    {
      id: "task-004",
      description: "Persist settings, rules and mods across sessions",
      status: "pending",
      dependencies: ["task-003"],
    },
  ],
};

export const EMPTY_MEMORY: AgentMemory = { tasks: [] };

export const DEFAULT_RULES = [
  "Please use the latest syntax for the current version of each programming language.",
  "Iterate on the existing code architecture. Do not create new files unless absolutely necessary.",
  "Operate with maximum efficiency and avoid any redundant or bloated code.",
];

export const DEFAULT_WORKSPACES: Workspace[] = [
  { id: "ws-default", name: "Project 1", lang: "TypeScript", path: "" },
];
