"""Render the deterministic machine-readable Mission API schema artifact."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from agent_workspace.core.mission_api_contracts import (
    ApprovalRecordRequest,
    EvidenceRecordRequest,
    MissionCreateRequest,
    MissionCapabilitiesResponse,
    MissionErrorResponse,
    MissionSystemCapabilities,
    MissionTransitionAPIRequest,
    MissionTransitionResponse,
    PlanAttachRequest,
    VerificationRecordRequest,
)
from agent_workspace.core.product_contracts import SCHEMA_VERSION
from agent_workspace.core.mission_contracts import ExecutionPlan
from agent_workspace.core.mission_model import Mission
from agent_workspace.core.mission_store import MissionPage, MissionTransitionPage


SCHEMA_ARTIFACT_VERSION = 1
_SCHEMA_MODELS: tuple[type[BaseModel], ...] = (
    Mission,
    ExecutionPlan,
    MissionCreateRequest,
    MissionCapabilitiesResponse,
    MissionErrorResponse,
    MissionSystemCapabilities,
    MissionTransitionAPIRequest,
    MissionTransitionResponse,
    MissionPage,
    MissionTransitionPage,
    PlanAttachRequest,
    ApprovalRecordRequest,
    EvidenceRecordRequest,
    VerificationRecordRequest,
)


def render_mission_schema() -> str:
    """Return the canonical JSON schema bundle for Mission contracts."""
    models = {
        model.__name__: model.model_json_schema(ref_template="#/$defs/{model}")
        for model in _SCHEMA_MODELS
    }
    bundle = {
        "artifact_version": SCHEMA_ARTIFACT_VERSION,
        "contract_schema_version": SCHEMA_VERSION,
        "models": models,
    }
    return json.dumps(bundle, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def _typescript_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            variants = [_typescript_type(item) for item in schema[key]]
            return " | ".join(dict.fromkeys(variants))
    if "allOf" in schema:
        return " & ".join(_typescript_type(item) for item in schema["allOf"])
    schema_type = schema.get("type")
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"readonly {_typescript_type(schema.get('items', {}))}[]"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            return "Readonly<Record<string, unknown>>"
        lines = ["{"]
        for name in sorted(properties):
            optional = "" if name in required else "?"
            lines.append(f"  readonly {name}{optional}: {_typescript_type(properties[name])};")
        lines.append("}")
        return "\n".join(lines)
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
    }.get(schema_type, "unknown")


def render_typescript_contracts(schema_text: str) -> str:
    bundle: dict[str, Any] = json.loads(schema_text)
    definitions: dict[str, dict[str, Any]] = {}
    for model_schema in bundle["models"].values():
        for name, definition in model_schema.get("$defs", {}).items():
            definitions.setdefault(name, definition)
    root_names = set(bundle["models"])
    for name in root_names:
        definitions[name] = bundle["models"][name]
    lines = [
        "/* Generated by python -m agent_workspace.mission_schema --typescript. */",
        "/* Do not edit manually; regenerate from schemas/mission_api.json. */",
        "",
        f"export const MISSION_API_SCHEMA_VERSION = {json.dumps(bundle['contract_schema_version'])} as const;",
        "",
    ]
    for name in sorted(definitions):
        if name in root_names:
            continue
        definition = definitions[name]
        if "enum" in definition:
            values = definition["enum"]
            lines.append(f"export const {name} = {{")
            for value in values:
                key = str(value).upper().replace("-", "_")
                lines.append(f"  {key}: {json.dumps(value, ensure_ascii=False)},")
            lines.extend(["} as const;", f"export type {name} = typeof {name}[keyof typeof {name}];", ""])
        else:
            lines.extend([f"export type {name} = {_typescript_type(definition)};", ""])
    for name in sorted(bundle["models"]):
        lines.extend([f"export type {name} = {_typescript_type(bundle['models'][name])};", ""])
    return "\n".join(lines)


def main() -> None:
    """Write the schema artifact to the repository or a supplied path."""
    if len(sys.argv) > 1 and sys.argv[1] == "--typescript":
        if len(sys.argv) != 3:
            raise SystemExit("usage: python -m agent_workspace.mission_schema --typescript output-path")
        artifact = Path(__file__).resolve().parents[1] / "schemas" / "mission_api.json"
        target = Path(sys.argv[2])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render_typescript_contracts(artifact.read_text(encoding="utf-8")), encoding="utf-8", newline="\n")
        return
    if len(sys.argv) > 2:
        raise SystemExit("usage: python -m agent_workspace.mission_schema [output-path]")
    target = Path(sys.argv[1]) if len(sys.argv) == 2 else Path(__file__).resolve().parents[1] / "schemas" / "mission_api.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_mission_schema(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
