"""Offline-first AST Static Analysis & Test Stub Generator (Phase 110).

Aligned with Universal Coding Agent Development Protocol v3.8.0, Anti-Corruption
Principle #4 (Typed Failures), and Principle #5 (Specification-First).

Provides 100% offline, zero-cloud-token AST static error detection, typed failure checks,
and automated test stub synthesis.
"""

from __future__ import annotations

import ast
import logging
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field

from agent_workspace.core.slm.engine import EdgeSLMEngine, EdgeSLMResponse

logger = logging.getLogger("OfflineASTAnalyzer")


class ASTDefectItem(BaseModel):
    """An AST static defect identified during offline scanning."""

    model_config = ConfigDict(extra="ignore")

    line_number: int
    rule_id: str
    message: str
    severity: str = "WARNING"  # INFO, WARNING, ERROR


class OfflineAnalysisResult(BaseModel):
    """Complete report of offline AST analysis."""

    model_config = ConfigDict(extra="ignore")

    file_path: str
    defects: List[ASTDefectItem] = Field(default_factory=list)
    has_bare_except: bool = False
    missing_docstrings_count: int = 0
    functions_found: List[str] = Field(default_factory=list)
    classes_found: List[str] = Field(default_factory=list)
    cloud_egress: bool = False


class OfflineASTAnalyzer:
    """Performs localized AST audits and generates automated unit test stubs."""

    def __init__(self, slm_engine: Optional[EdgeSLMEngine] = None) -> None:
        self.slm_engine = slm_engine or EdgeSLMEngine()

    def audit_source(self, code_content: str, file_path: str = "inline.py") -> OfflineAnalysisResult:
        """Parses and inspects Python source code using standard library AST."""
        result = OfflineAnalysisResult(file_path=file_path)

        try:
            tree = ast.parse(code_content, filename=file_path)
        except SyntaxError as e:
            result.defects.append(
                ASTDefectItem(
                    line_number=e.lineno or 1,
                    rule_id="AST-SYNTAX-ERR",
                    message=f"SyntaxError: {e.msg}",
                    severity="ERROR",
                )
            )
            return result

        for node in ast.walk(tree):
            # 1. Anti-Corruption #4: Check for bare except: blocks
            if isinstance(node, ast.ExceptHandler):
                if node.type is None:
                    result.has_bare_except = True
                    result.defects.append(
                        ASTDefectItem(
                            line_number=node.lineno,
                            rule_id="ANTI-CORRUPTION-TYPED-FAILURES",
                            message="Bare 'except:' statement detected. Must catch typed exception.",
                            severity="ERROR",
                        )
                    )

            # 2. Check Functions and docstrings
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                result.functions_found.append(node.name)
                docstring = ast.get_docstring(node)
                if not docstring and not node.name.startswith("_"):
                    result.missing_docstrings_count += 1
                    result.defects.append(
                        ASTDefectItem(
                            line_number=node.lineno,
                            rule_id="DOCSTRING-MISSING",
                            message=f"Public function '{node.name}' lacks a descriptive docstring.",
                            severity="INFO",
                        )
                    )

            # 3. Check Classes
            elif isinstance(node, ast.ClassDef):
                result.classes_found.append(node.name)

        return result

    def generate_test_stubs(self, code_content: str, module_name: str = "target_module") -> str:
        """Synthesizes structured pytest test stubs based on AST extracted signatures."""
        analysis = self.audit_source(code_content, f"{module_name}.py")

        lines = [
            f'"""Automated Unit Test Stubs for {module_name} (Generated by OfflineASTAnalyzer)."""\n',
            "from __future__ import annotations\n",
            "import pytest\n",
        ]

        if analysis.classes_found:
            for cls in analysis.classes_found:
                lines.append(f"\nclass Test{cls}:")
                lines.append(f'    """Test suite for {cls}."""\n')
                lines.append(f"    def test_{cls.lower()}_initialization(self):")
                lines.append(f'        """Verify {cls} initializes with default state."""')
                lines.append("        # Arrange & Act")
                lines.append("        pass\n")

        if analysis.functions_found:
            for fn in analysis.functions_found:
                if not fn.startswith("__"):
                    lines.append(f"\ndef test_{fn}_baseline_execution():")
                    lines.append(f'    """Verify {fn} executes and adheres to contracts."""')
                    lines.append("    # Arrange, Act & Assert")
                    lines.append("    pass\n")

        return "\n".join(lines)

    async def propose_quick_fix(self, defect: ASTDefectItem, context_snippet: str) -> Optional[EdgeSLMResponse]:
        """Prompts local Edge SLM to propose a non-cloud, instant patch for a defect."""
        prompt = (
            f"Fix the following AST defect in Python code:\n"
            f"Defect: {defect.rule_id} at line {defect.line_number} - {defect.message}\n"
            f"Code context:\n```python\n{context_snippet}\n```\n"
            f"Return only the minimal fixed Python code chunk."
        )
        return await self.slm_engine.generate_completion(prompt, max_tokens=512)
